version: '3.8'

services:
  app-rust:
    build:
      context: ./rust-backend
      dockerfile: Dockerfile
    container_name: personal-drive-backend-rust
    restart: unless-stopped
    ports:
      - "4001:4000"
    env_file:
      - .env