version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-drive-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env